version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - REPO=$DOCKERHUB_USERNAME/mindtrack-app
      - IMAGE_TAG=$CODEBUILD_BUILD_NUMBER

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPO:$IMAGE_TAG .

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $REPO:$IMAGE_TAG

      - echo Deploying to EKS...
      - kubectl set image deployment/mindtrack-app mindtrack-app=$REPO:$IMAGE_TAG

artifacts:
  files:
    - imagedefinitions.json
