version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo Logging into Docker Hub
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - echo Configuring EKS access
      - aws eks update-kubeconfig --region ap-south-1 --name mindtrack-cluster

      - aws sts get-caller-identity
      - kubectl config current-context
      - kubectl get ns

  build:
    commands:
      - echo Building image
      - docker build -t $DOCKER_USERNAME/mindtrack-app:v1 .

  post_build:
    commands:
      - echo Pushing image
      - docker push $DOCKER_USERNAME/mindtrack-app:v1

      - kubectl rollout restart deployment/mindtrack-app
      - kubectl rollout status deployment/mindtrack-app
