apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindtrack-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mindtrack-app
  template:
    metadata:
      labels:
        app: mindtrack-app
    spec:
      containers:
        - name: mindtrack-app
          image: DOCKERHUB_USERNAME/mindtrack-app:latest
          ports:
            - containerPort: 3000
